### ISSUE TITLE
switch config from an array of tables

### ISSUE THREAD

**Issue by joshuadavidthomas** [joshuadavidthomas/shadow#11]
instead of an array of tables, the table name should be based on something unique. maybe the command or the alias, but something to lock it in.

```toml
[[shadows]]
original = "find"
replacement = "fd"

[[shadows]]
original = "cat"
replacement = "bat --paging=never"
```

vs

```toml
[find]
original = "find"
replacement = "fd"
# or
[aliases.fd]
original = "find"
```

Or even just a UUID or some random identifier.
